[package]
name = "voxel_core"
version = "0.1.0"
edition = "2024"

[dependencies]
"voxel_rendering" = { path = "../voxel_rendering" }
"voxel_world" = { path = "../voxel_world" }
winit = { version = "0.30.13" }
glam = "0.33.3"

[dependencies.sdl3]
version = "0.18.4"
features = ["raw-window-handle", "build-from-source"]